version: "3.7"

services:
  api:
    build: .
    ports:
      - 3001:3000
    environment:
      SECRET: patata
    volumes:
      - ./src:/usr/src/app
    command: npm run dev
    networks:
      - keepsecrets
networks:
  keepsecrets:
    name: keepsecrets
    external: true
