version: "3.7"

services:
  api:
    build: .
    ports:
      - 3001:3000
    environment:
      JWT_KEY: 9178c50c378bc98ac3a0083d6fe36e9fdc80d9e25dfac530
    volumes:
      - ./src:/usr/src/app
    command: npm run dev
    networks:
      - keepsecrets
networks:
  keepsecrets:
    name: keepsecrets
    external: true
